// http://bioinformaticsalgorithms.com/data/debugdatasets/replication/PatternCount.pdf

#include "util/io.h"
#include "util/string-view.h"

static int
patternCount(StringView text, StringView pattern) {
    size_t tlen = text.size;
    size_t plen = pattern.size;

    int count = 0;

    for (int i = 0; i <= tlen - plen; i++) {
        if (text.substr(i, plen) == pattern) {
            count++;
        }
    }

    return count;
}

static void
test(StringView text, StringView pattern) {
    int count = patternCount(text, pattern);
    sout << count << '\n';
}

int
main() {
    test("GCGCG", "GCG"); // 2
    test("ACGTACGTACGT", "CG"); // 3
    test("AAAGAGTGTCTGATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAATAATTACAGAGTACACAACATCCAT", "AAA"); // 4
    test("AGCGTGCCGAAATATGCCGCCAGACCTGCTGCGGTGGCCTCGCCGACTTCACGGATGCCAAGTGCATAGAGGAAGCGAGCAAAGGTGGTTTCTTTCGCTTTATCCAGCGCGTTAACCACGTTCTGTGCCGACTTT", "TTT"); // 4
    test("GGACTTACTGACGTACG", "ACT"); // 2
    test("ATCCGATCCCATGCCCATG", "CC"); // 5
    test("CTGTTTTTGATCCATGATATGTTATCTCTCCGTCATCAGAAGAACAGTGACGGATCGCCCTCTCTCTTGGTCAGGCGACCGTTTGCCATAATGCCCATGCTTTCCAGCCAGCTCTCAAACTCCGGTGACTCGCGCAGGTTGAGTA", "CTC"); // 9
    test("ATGCAAAGCCGGTGTGAGTCGCAAAGCCATCAAAGCCAAATCAAAGCCCTCAAAGCCTGATTTCGCAAAGCCGCCATCAAAGCCAGCAAAGCCTTTCAAAGCCCCAAAGCCTTACGGCTGTGCAAAGCCAGGTTGATGTCTGCCAAAGCCGACAAAGCCTCAAAGCCCAAAGCCACCAAAGCCACAAAGCCGTCCAAAGCCCCAAAGCCCAAAGCCGACAAAGCCGCAAAGCCCCAAAACAAAGCCGCTAAACCCCCAAAGCCCCGCAAAGCCCGTTCAAAGCCCAAAGCCATTGGCCGGCGCCCAAAGCCAATCAAAGCCTTCAAAGCCTGCAAAGCCCGCAGCAAAGCCACAAAGCCGCAAAGCCCAAAGCCCAAAGCCCCAAAGCCCTGTCCCAAAGCCCAAAGCCTCCAAAGCCCAAAGCCAAGTTTCCTTGACAAAGCCCCAAAGCCGCAAAGCCCAAAGCCTGCAAAGCCATGCAAAGCCGACCAAAGCCTCGCAAAGCCGGCGCTGACCAAAGCCAAAGTTCAAAGCCCCAAAGCCCAAAGCCCCAAAGCCCGCCAAAGCCCAAAGCCGCAAAGCCGACAAAGCCGGCAAAGCCCCACAAAGCCGCAAAGCCCACATCAAAGCCTACACAAAGCCAACAAAGCCTGCAAAGCCCTATGGACCAAAGCCTTCAAAGCCGCAAAGCCAGGTCAAAGCCAAGATCAAAGCCGGCAAAGCCCCAAAGCCAGCAAAGCCGTGTTCAAAGCCACAAAGCCCAAAGCCTCGTTACAAAGCCGGCAAAGCCATGCAAAGCCGTCAAAGCCCAAAGCCCTCAAAGCCCAAAGCCCAAAGCCGTTCAAAGCCCAAAGCCCTCAGTACGCCAAAGCCTCCAAAGCCTGCCAGGTACAAAGCCCCAAAGCCACAAAGCCCAATGCGGCAAAGCCCAAAGCCCAAAGCCGGCAAAGCCCAAAGCCCTACTCAAAGCCTCGTCTGGATCGACAAAGCCCAAAGCCCAAAGCCCCAAAGCCTCTTTCCAAAGCCTCCAAAGCCCAAAGCCTAGACAAAGCCCAAAGCC", "CAAAGCCCA");
    return 0;
}
